modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="among_us"
version="1.0.0"
displayName="Among Us Mod"
displayURL="http://jdloghead.duckdns.org"
logoFile="logo.png"
credits="jdloghead"
authors="jdloghead"
description="sussy mod i made for some reason idk guess i was bored"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.among_us]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration